version: '3.1'

services:

  bugatti-api:
    image: "gcmedia/api:${TAG}"
    env_file:
      - .env
    restart: always
    networks:
      - bugatti-net
    ports:
      - "3000:3000"
    labels:
      - "traefik.backend=api"
      - "traefik.docker.network=bugatti-net"
      - "traefik.enable=true"
      - "traefik.protocol=http"
      - "traefik.frontend.rule=Host:api.thegc.cf"
      - "traefik.port=3000"
networks:
  bugatti-net:
    external: true
