version: '3.1'

services:

  bugatti-api:
    image: tgalske/bugatti-api
    env_file:
      - .env
    restart: always
    networks:
      - bugatti-net
    ports:
      - "3000:3000"

networks:
  bugatti-net:
    external: true
